language: csharp
# Mono is used to build .NET on Linux--we don't need it with Core.
mono: none
# Needed to run commands in the Xenial CLI
sudo: required
# The version of Ubuntu to run the Travis virtual machine -- needed for .NET Core
dist: xenial
# Your SDK version, not your run-time version
dotnet: 2.2 
script: # These commands are executed in the Travis VM just like you would on your local machine
    # Use a "cd" command to move the Travis command line prompt into your solution directory
    - cd /home/travis/build/jmacgregor-accenture/maxJohnCI-Kata/DotNet/CIKataFrontEnd/CIKataFrontEnd.React/
    # if your project has tests, you can skip "restore" and "build" and just use "test" command
    - npm test
    - cd ../../CIKataBackEnd/
    - dotnet test
