version: '3'
services:
  frontend:
    image: jmacaccenture/kata_attempt_one:frontend
    #build: './DotNet/CIKataFrontEnd'
    ports: 
      - "5001:80"
    #volumes:
    #  - ./DotNet/CIKataFrontEnd/certificates/server.crt:/etc/ssl/certs/server.crt
  backend:
    image: jmacaccenture/kata_attempt_one:backend
    #build: './DotNet/CIKataBackEnd'
    ports: 
      - "8001:80"