version: '3'
services:
  frontend:
    #image: jmacaccenture/ciexplore:front
    build: './DotNet/CIKataFrontEnd'
    ports: 
      - "5001:80"
    volumes:
      - ./DotNet/CIKataFrontEnd/certificates/server.crt:/etc/ssl/certs/server.crt
  backend:
   #image: jmacaccenture/ciexplore:back
    build: './DotNet/CIKataBackEnd'
    ports: 
      - "8001:80"